import Head from "next/head";
// import Image from "next/image";
import Script from "next/script";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        h2 {
          font-size: 38px;
        }
        h3 {
          font-size: 28px;
        }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keyword"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="">Hunting Coder</span>
        </h1>
        <div className={styles.imagewrap}>
          {/* <Image
            className={styles.myImg}
            src="/homeimg.jpg"
            alt="home"
            // layout="fill"
            width={237}
            height={158}
          /> */}
          <img
            className={styles.myImg}
            src="/homeimg.jpg"
            width={237}
            height={158}
            alt="home"
          />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How t learn Javascript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How t learn Javascript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How t learn Javascript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
